// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/Noush-012/project-ecommerce-microservice/user-service/pkg/api"
	"github.com/Noush-012/project-ecommerce-microservice/user-service/pkg/client"
	"github.com/Noush-012/project-ecommerce-microservice/user-service/pkg/config"
	"github.com/Noush-012/project-ecommerce-microservice/user-service/pkg/db"
	"github.com/Noush-012/project-ecommerce-microservice/user-service/pkg/repository"
	"github.com/Noush-012/project-ecommerce-microservice/user-service/pkg/service"
	"github.com/Noush-012/project-ecommerce-microservice/user-service/pkg/usecase"
)

// Injectors from wire.go:

func InitiateAPI(cfg *config.Config) (*api.ServeServer, error) {
	gormDB, err := db.ConnToDB(cfg)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(gormDB)
	orderClient, err := client.NewOrderClient(cfg)
	if err != nil {
		return nil, err
	}
	userService := usecase.NewUserUseCase(userRepository, orderClient)
	userServiceServer := service.NewUserServiceServer(userService, userRepository)
	serveServer, err := api.NewGRPCServer(cfg, userServiceServer)
	if err != nil {
		return nil, err
	}
	return serveServer, nil
}
